var gec={path:{cdnJs:"/f/2015-ec/m/js/lib/",baseCdn:"//s.3.elcomercio.pe.s3-website-us-east-1.amazonaws.com",jquery:"//s.3.elcomercio.pe.s3-website-us-east-1.amazonaws.com/f/2214-ec/js/lib/jquery.js",peruid:"http://s.peruid.pe.s3-website-us-east-1.amazonaws.com/f/scripts/peruid-1.1.js",comments:"se autogenera"},mem:[],env:null,log:{loaded:[]},thisJs:document.getElementById("js-core"),ver:null,ios:navigator.userAgent.match(/iPhone|iPad|iPod/i)?!0:!1,dom:{},utils:{cookie:{read:function(a){return RegExp(a+
"=([^;]+)").test(unescape(document.cookie))?RegExp.$1:null},save:function(a,c,b){b="number"==typeof b?{expires:b}:b;a=[escape(a)+"="+escape(c)];b&&(b.expires&&("number"==typeof b.expires&&(c=new Date,c.setTime(c.getTime()+864E5*b.expires),b.expires=c),a.push("expires="+b.expires.toGMTString())),b.path&&a.push("path="+b.path),b.domain&&a.push("domain="+b.domain),b.secure&&a.push("secure"));document.cookie=a.join("; ")}},round:function(a,c){c=parseFloat(c?c:2)+1;c=parseFloat("10000".substr(0,c));return Math.round(a*
c)/c},preventDefault:function(a){a.preventDefault?a.preventDefault():a.returnValue=!1},stopAndPreventDefault:function(a){this.preventDefault(a);a.stopPropagation?a.stopPropagation():a.cancelBubble=!0},exec:function(a,c){var b,d;if("string"==typeof a&&(b=a.split(","),d=[],0<b.length))for(var e=0;e<b.length;e++){var f=$.trim(b[e]);if(!d[f])if("function"==typeof gec.ui[f])d[f]=1,$(".ui-"+f)[f]();else if("function"==typeof gec.fn[f])gec.fn[f]()}},eventBind:function(a){var c=!0,b;if(!a.element.jquery){c=
a.event.stopPropagation?!0:!1;a.event.stopPropagation?a.event.stopPropagation():(c=!1,a.event.cancelBubble&&(a.event.cancelBubble=!0));a.event.preventDefault?a.event.preventDefault():a.event.returnValue=!1;var d=$(a.element);"function"==typeof a.callback&&(b=a.callback({element:d,mom:d}));new gec.ui[a.ui](b.mom);c&&(a=b.element.data("event")||"click.gecui",b.element.trigger(a));return!0}return!1}},fn:{loadJs:function(a){var c;if(a)console.log("cargando... ",a),gec.ver=gec.ver||(gec.thisJs.src.match(/ver=(.?)*/i)||
["ver=281080"])[0],c=document.createElement("script"),c.type="text/javascript",c.async=!0,c.src=(gec.path[a]||("pro"==gec.env?gec.path.baseCdn:"")+gec.path.cdnJs+a+".js")+"?"+gec.ver,c.addEventListener("load",function(){gec.log.loaded[a]=!0}),gec.thisJs.parentNode.insertBefore(c,gec.thisJs);else{c=gec.thisJs.getAttribute("data-js").replace(/\s+/g,"").split(",");for(var b=0;b<c.length;b++)if(!gec.log.loaded[c[b]]&&"comments"!=c[b]&&""!=c[b])if(gec.fn.otherJs[c[b]])gec.fn.otherJs[c[b]]();else gec.fn.loadJs(c[b])}},
otherJs:{},track:function(a){for(var c in a)switch(c){case "nid":gec.nid&&$.post("/index.php/callback/notas/visitas/?rnd"+Math.random().toString().substring(4),{nid:gec.nid})}},search:function(a,c){var b=$(c),d=b.siblings("input");gec.utils.stopAndPreventDefault(a);b.hasClass("icon-close")?b.removeClass("icon-close").addClass("icon-search").closest("ul").removeClass("state-search"):b.data("trigger")||(b.removeClass("icon-search").addClass("icon-close").closest("ul").addClass("state-search"),d.get(0).focus());
b.data("binded")||(d.on("blur",function(a){b.data("trigger",!0).trigger("click");setTimeout(function(){b.data("trigger",!1)},300)}),b.data("binded",!0))},buscamas:function(a,c){c.gesture&&(c.gesture.stopPropagation(),c.gesture.preventDefault());c.preventDefault();c.stopPropagation();var b=encodeURIComponent(a.b.value);document.location.href=a.getAttribute("action")+b.replace(/%20/g,"+")+"?ft=buscar";return!1},dim:function(a,c){c=c||"max";return Math[c](Math[c](document.body["scroll"+a],document.documentElement["scroll"+
a]),Math[c](document.body["offset"+a],document.documentElement["offset"+a]),Math[c](document.body["client"+a],document.documentElement["client"+a]))},toggle:function(a,c){gec.utils.preventDefault(c);var b=$(a),d=b.data("family")?b[b.data("family")](b.data("target")||""):$(b.data("target")),e=b.data("class")||"ui-active",f=b.data("slide")||!1;d.hasClass(e)?(d.removeClass(e),b.removeClass(e),f&&d.slideUp("fast")):(d.addClass(e),b.addClass(e),f&&d.slideDown("fast"))},validateControl:function(a,c,b){var d=
$(c),e,f=d.data("restrict"),g=d.data("require")||!1,h={alpha:/^[a-zA-Z\s\u00c3\u00b1\u00c3\u2018\']+$/,alphanumeric:/^\w+$/,integer:/^\d+$/,decimal:/^[\d|\.,]+$/,date:/^[\d|\-\/]+$/,email:eval("/[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/"),all:/([^\s])/};e=a.which||window.event&&window.event.keyCode||0;if("blur"!=a.type||!g&&"email"!=f)"keypress"!=a.type||"email"==f||!e||13>=e||String.fromCharCode(e).match(h[f])||
a.preventDefault();else if(a=0<="checkbox,radio".indexOf(c.type)?c.checked?c.value:"":c.value,g&&(e=d.closest(".ui-row").removeClass("ui-error"),b&&e.children(".ui-message-error").remove()),g&&""==$.trim(a)||f&&a&&!a.match(h[f]))d.closest(".ui-row").addClass("ui-error"),b&&d.closest(".ui-row").append('<div class="ui-message-error">'+(c.getAttribute("data-message")||"Este valor es incorrecto o es requerido")+"</>")},validate:function(a,c,b){var d=a.jquery?!1:(a=$(a),!0);a.each(function(){var a=$(this),
f=$("[data-restrict],[data-require]",a);f.filter('[data-restrict]:not([data-restrict="email"])').bind("keypress",function(b){gec.fn.validateControl(b,this,a.data("show-message")||!1)});f.filter('[data-require],[data-restrict="email"]').bind("blur",function(b){gec.fn.validateControl(b,this,a.data("show-message")||!1)});a.on("submit",function(g){var h;f.filter('[data-require],[data-restrict="email"]').trigger("blur");h=0<$(".ui-error",a).length;c=d&&"function"==typeof b?b:c;if(h||"function"!=typeof c)return!h;
c(g,a);return!1})});d&&(c.preventDefault(),a.removeAttr("onsubmit").trigger("submit"))},redirect:function(a){window.location=$(a).val()},sharemail:function(a,c){c.gesture&&(c.gesture.stopPropagation(),c.gesture.preventDefault());gec.utils.stopAndPreventDefault(c);var b=$(a),d=a.getAttribute("title")||"Compartir por e-mail",e=function(){var a=$("#"+b.data("toggle"));a.hasClass("showshare")?a.removeClass("showshare"):a.addClass("showshare")};b.data("done")||(b.after(['<div class="box-send"><form class="ui-form " data-show-message="true"><div class="ui-head">',
"<span>"+d+"</span>",'</div><div class="ui-body"><div class="ui-row"><input autocomplete="off" class="i_text" type="text" name="nombre" placeholder="Tu nombre" data-require="true"></div><div class="ui-row"><input autocomplete="off"  class="i_text" type="text" name="nombreamigo" placeholder="Nombre de tu amigo" data-require="true"></div><div class="ui-row"><input  class="i_text" type="text" name="emailamigo" placeholder="Email de tu amigo" data-restrict="email" data-require="true"></div>','<input type="hidden" name="titulo" value="'+
a.getAttribute("data-title")+'">','<input type="hidden" name="pagina" value="'+a.getAttribute("data-link")+'">','</div><div class="ui-foot ui-row"><button type="submit">Enviar</button></div></form></div>'].join("")),$form=b.siblings(".box-send").find("form"),gec.fn.validate($form,function(a){gec.utils.stopAndPreventDefault(a);$.post(b.data("post"),$form.serialize(),function(a){a.succes&&$(".ui-body",$form).append('<div class="tx-message">'+a.message+"</div>");setTimeout(function(){e();$(".tx-message",
$form).remove()},3E3);$(".i_text",$form).val("")},"json")}));b.data("done",!0);e()},sondeo:function(a,c){var b=$(a);c.preventDefault();b.hasClass("sondeo-ver")?b.closest(".poll-pre").hide().siblings(".poll-suf").fadeIn("slow"):b.is("form")?0<b.find("input[type=radio]").filter(":checked").length?$.post(b.attr("action")+"?rnd="+Math.random().toString().substring(2),b.serialize(),function(a){gec.utils.cookie.save("idqpe"+b.closest(".ui-encuesta-render").data("id"),"1",{expires:1,path:"/"});b.data("redirect")?
window.location=b.data("redirect"):(b.siblings(".poll-suf").show().html(a),b.remove())}):b.find(".er-noselect").fadeIn("fast").delay(3E3).fadeOut("fast"):b.hasClass("sondeo-volver")&&b.closest(".poll-suf").hide().siblings(".poll-pre").fadeIn("slow")},nextNews:function(){if(!gec.ios){var a=$(".box-swipe > .ui-prev"),c=$(".box-swipe > .ui-next"),b=0,d=0,e,f,g,h=$(window),k=$("body"),m=!0;$("#ec-content").on("touchstart.libui touchmove.libui touchend.libui",function(n){if(k.hasClass("dragging"))return!1;
switch(n.type){case "touchstart":b=n.originalEvent.touches[0].pageX;d=h.scrollTop();e=h.width();a.add(c).css({transition:"none"});m=!1;break;case "touchmove":n=n.originalEvent.touches[0].pageX-b;var u=h.scrollTop()-d,r=100*n/e;if(0==u&&30<n||0==u&&-30>n)m=!0;0<n&&m&&0<a.length?(f=100*r/50,a.css({transform:"translateX("+(100<f?100:f)+"%)",opacity:f/100})):0>n&&m&&0<c.length&&(g=100*r/50,c.css({transform:"translateX("+(-100>g?-100:g)+"%)",opacity:-1*g/100}));break;case "touchend":if(100<f&&0<a.length)return a.addClass("loading"),
window.location.href=a.attr("href"),!1;if(-100>g&&0<c.length)return c.addClass("loading"),window.location.href=c.attr("href"),!1;a.add(c).css({transition:"transform .5s ease",transform:"translateX(0)"})}})}},archivo:function(){(function(){$("#filter-action").find("input").on("change",function(){var a=$("#ec-archivo-in"),c=$(this);c.is(":checked")?(c.parent("label").addClass("active"),$(this.value,a).closest(".f-nota").slideDown(200)):(c.parent("label").removeClass("active"),$(this.value,a).closest(".f-nota").slideUp(200));
setTimeout(function(){$(window).trigger("scroll.libui")},210)})})()},fheader:function(){var a=$("#ec-header"),c=a.outerHeight();$(window).on("scroll touchmove",function(){$(this).scrollTop()>=c?a.hasClass("header-follow")||a.addClass("header-follow"):a.removeClass("header-follow")})},headershow:function(){var a=0,c=0,b=$("header"),d=!1,e=$(window);e.on("touchend touchstart scroll",function(f){switch(f.type){case "touchstart":a=e.scrollTop();d=!0;break;case "touchend":var g,h=setInterval(function(){g===
e.scrollTop()?(clearInterval(h),d=!1,a>=g||50>=g?b.removeClass("out"):a<g&&50<g&&b.addClass("out")):g=e.scrollTop()},50);break;case "scroll":d||(h=setInterval(function(){c===e.scrollTop()?(clearInterval(h),50>=e.scrollTop()&&b.removeClass("out")):c=e.scrollTop()},50))}})},sharebox:function(a,c){gec.utils.stopAndPreventDefault(c);var b=$(a).data("params"),b=$(['<div class="box-share" id="box-share" style="display:block;"><a href="#" class="icon-close ui-cancel" ></a><h2>Compartir</h2>',"<h3>"+b.title+
"</h3>",'<ul class="social-list">','<li><a href="https://www.facebook.com/sharer/sharer.php?u='+b.url+"&amp;t="+encodeURI(b.title)+"\" onclick=\"if (typeof ga == 'function') ga('send', 'event', 'Version-movil-botones-compartir', 'facebook', '"+b.url+'\');" target="_blank"><i class="icon-fb"></i>Facebook</a></li>','<li><a href="https://twitter.com/intent/tweet?original_referer='+b.url+"&amp;text="+encodeURI(b.title)+"&amp;tw_p=tweetbutton&amp;url="+b.url+"&amp;via=elcomercio\" onclick=\"if (typeof ga == 'function') ga('send', 'event', 'Version-movil-botones-compartir', 'twitter', '"+
b.url+'\');" target="_blank"><i class="icon-tw"></i>Twitter</a></li>','<li><a href="https://plus.google.com/share?url='+b.url+"\" onclick=\"if (typeof ga == 'function') ga('send', 'event', 'Version-movil-botones-compartir', 'googleplus', '"+b.url+'\');" target="_blank"><i class="icon-gp"></i>Google+</a></li>','<li><a href="whatsapp://send?text='+encodeURI(b.title)+" - "+b.url+"\" onclick=\"if (typeof ga == 'function') ga('send', 'event', 'Version-movil-botones-compartir', 'WhatsApp', '"+b.url+'\');"><i class="icon-wa"></i> WhatsApp</a></li>',
"</ul></div>"].join(""));gec.ui.movilPopup({target:b,element:$(a),callback:function(a){}})}},ui:{zoomFigure:function(a,c){function b(){g.fadeOut("fast",function(){$(this).remove();f.removeClass("ui-menuover-on")})}function d(a){if(!gec.log.loaded.hammer)return setTimeout(function(){d(a)},300),!1;var b=new Hammer(a,{});b.get("pinch").set({enable:!0});var c=0,f=0,e=1,g=1,k=0,h=0,t=0,p=0,q="";b.on("doubletap pan pinch panend pinchend",function(b){if("doubletap"==b.type){q="translate3d(0, 0, 0) scale3d(2, 2, 1) ";
g=e=2;try{"matrix(1, 0, 0, 1, 0, 0)"!=window.getComputedStyle(a,null).getPropertyValue("transform").toString()&&(q="translate3d(0, 0, 0) scale3d(1, 1, 1) ",g=e=1)}catch(d){}a.style.webkitTransform=q;q=""}1!=e&&(c=k+b.deltaX,f=h+b.deltaY,t=Math.ceil((e-1)*a.clientWidth/2),p=Math.ceil((e-1)*a.clientHeight/2),c>t&&(c=t),c<-t&&(c=-t),f>p&&(f=p),f<-p&&(f=-p));"pinch"==b.type&&(e=Math.max(0.999,Math.min(g*b.scale,4)));"pinchend"==b.type&&(g=e);"panend"==b.type&&(k=c<t?c:t,h=f<p?f:p);1!=e&&(q="translate3d("+
c+"px,"+f+"px, 0) scale3d("+e+", "+e+", 1)");q&&(a.style.webkitTransform=q,a.style.transform=q)})}var e=$(a);$(window);var f=$("body"),g,h=e.data("option");if(gec.utils.eventBind({element:a,event:c,ui:"zoomFigure",callback:function(a){a.element.removeAttr("onclick");return a}}))return!1;gec.log.loaded.hammer||gec.fn.loadJs("hammer");var k=$(['<div class="box-imgzoom"><div class="header-box-imgzoom"><div class="nota-share"><ul>','<li class="fb"><a href="https://www.facebook.com/sharer/sharer.php?u='+
window.location.href+'"><i class="icon-fb"></i></a></li>','<li class="tw"><a href="https://twitter.com/intent/tweet?original_referer='+window.location.href+"&text="+encodeURI(document.title)+"&tw_p=tweetbutton&url="+window.location.href+'&via=elcomercio"><i class="icon-tw"></i></a></li>','<li class="wa"><a href="whatsapp://send?text='+encodeURI(document.title)+" - "+window.location.href+'"><i class="icon-wa"></i></a></li>','</ul></div><a href="" class="ui-close icon-close"></a></div><div class="image-inner"><figure class="zoom-figure">',
'<img src="'+h.photo+'" alt="">','</figure></div><div class="img-caption">',"<p>"+decodeURIComponent(h.caption)+"</p>","</div></div>"].join(""));k.find(".ui-close").on("click",function(a){a.preventDefault();b()});e.on("click.gecui",function(a){a.preventDefault();g=k.clone(!0);d(g.find(".zoom-figure")[0]);f.addClass("ui-menuover-on").append(g)})},comentsOver:function(a,c){function b(a){var b=a.outerWidth(),c,d,f,e;a.on("touchstart touchend touchmove",function(a){switch(a.type){case "touchstart":e=
a.originalEvent.touches[0].pageX;f=(new Date).getTime();break;case "touchmove":a.preventDefault();c=a.originalEvent.touches[0].pageX-e;d=100*c/b;break;case "touchend":250>(new Date).getTime()-f&&15<d&&h(!1)}})}gec.utils.stopAndPreventDefault(a);if(gec.log.loaded.peruid){var d=$(c),e=d.data("params"),f=$(e.dim),g=$(e.target),h=function(a){a?($("html").addClass("ui-ios-menuover-on"),d.addClass("ui-menuover-show"),f.addClass("ui-dimmed"),g.addClass("ui-menuover-visible").trigger("show")):($("html").removeClass("ui-ios-menuover-on"),
d.removeClass("ui-menuover-show"),f.removeClass("ui-dimmed"),g.removeClass("ui-menuover-visible").trigger("hide"))};d.data("binded")||(f.on("click.menuoverui",function(a){h(!1)}),g.on("close",function(){h(!1)}),g.on("show",function(){b(f)}).on("hide",function(){f.off("touchstart touchend touchmove")}),gec.dom.coments=g,gec.fn.otherJs.comments(),d.data("binded",!0));h(!d.hasClass("ui-menuover-show"))}},menuOver:function(a,c){function b(a){var b=a.outerWidth(),c,d,f,e;a.on("touchstart touchend touchmove",
function(a){switch(a.type){case "touchstart":e=a.originalEvent.touches[0].pageX;f=(new Date).getTime();break;case "touchmove":a.preventDefault();c=a.originalEvent.touches[0].pageX-e;d=100*c/b;break;case "touchend":250>(new Date).getTime()-f&&-15>d&&m(!1)}})}gec.utils.stopAndPreventDefault(a);var d=$(c),e=d.data("params"),f=$("#ec-content"),g=$(e.dim),h=0,k=$(e.menuover),m=function(a){a?(gec.dom.coments&&gec.dom.coments.trigger("close"),h=$(document).scrollTop(),$("html").addClass("ui-ios-menuover-on"),
d.addClass("ui-menuover-show"),g.addClass("ui-dimmed"),k.addClass("ui-menuover-visible").trigger("show"),f.css({transform:"translateY("+-1*h+"px)","-webkit-transform":"translateY("+-1*h+"px)"})):($("html").removeClass("ui-ios-menuover-on"),d.removeClass("ui-menuover-show"),g.removeClass("ui-dimmed"),k.removeClass("ui-menuover-visible").trigger("hide"),f.css({transform:"none","-webkit-transform":"none"}),$(document).scrollTop(h))};d.data("binded")||(g.on("click.menuoverui",function(a){m(!1)}),k.on("close",
function(){m(!1)}),k.on("show",function(){b(g)}).on("hide",function(){g.off("touchstart touchend touchmove")}),gec.dom.menu=k,d.data("binded",!0));m(!d.hasClass("ui-menuover-show"))},sharemail:function(a,c){function b(a,b){var c=$(b);gec.ui.validate(c.find("form"),function(){var a;c.hasClass("ui-wait")||(c.addClass("ui-wait"),$.post(e.data("post"),c.find("form").serialize(),function(b){b.succes?c.prev().trigger((e.data("event")||"click")+".libui"):(a=$('<div class="ui-row ui-server-error">'+b.message+
"</div>"),c.removeClass("ui-wait"),c.find("div.ui-body").append(a),setTimeout(function(){a.fadeOut("slow")},3E3))},"json"))})}function d(){var a=e.data("captcha")||"",b=e.data("title")||"Compartir por e-mail";a&&(a='<div class="ui-row"><img alt="captcha" src="'+a+'" class="ui-captcha" /><input type="text" name="captcha" class="input-captcha" placeholder="Captcha" data-restrict="alpha" data-require="true"></div>');e.data({content:['<form class="ui-form" data-show-message="false"><div class="ui-head">',
"<span>"+b+"</span>","<a class=\"ui-cancel\" onclick=\"$(this).closest('.ui-sharemail').prev().trigger('"+(e.data("event")||"click")+".libui')\"><span>X</span></a>",'</div><div class="ui-body"><div class="ui-row"><input type="text" name="nombre" placeholder="Tu nombre" data-require="true"></div><div class="ui-row"><input type="text" name="nombreamigo" placeholder="Nombre de tu amigo" data-require="true"></div><div class="ui-row"><input type="text" name="emailamigo" placeholder="Email de tu amigo" data-restrict="email" data-require="true"></div>',
'<input type="hidden" name="titulo" value="'+e.data("title")+'">','<input type="hidden" name="pagina" value="'+e.data("link")+'">',a,'</div><div class="ui-foot ui-row"><button type="submit">Enviar</button></div></form>'].join(""),event:e.data("event")||"click",extraclass:"ui-sharemail",position:e.data("position")||"bottom"})}var e=$(a);if(gec.utils.eventBind({element:a,event:c,ui:"tooltip",callback:function(a){d();"tap"==c.type?(a.element.data("event",c.type),a.element.off(c.type)):a.element.removeAttr("on"+
("mouseenter"==a.element.data("event")?"mouseover":a.element.data("event")));a.mom.on("onrender",b);return a}}))return!1;d();new gec.ui.tooltip(e);return!1},tooltip:function(a,c){var b,d,e,f,g,h,k;if(gec.utils.eventBind({element:a,event:c,ui:"tooltip",callback:function(a){a.element.removeAttr("on"+("mouseenter"==a.element.data("event")?"mouseover":a.element.data("event")));return a}}))return!1;b=a;a=a[0];b.on(b.data("event")+".libui",function(c){c.preventDefault();c.stopPropagation();e=b.next(".ui-tooltip");
if(0<e.length)e.remove(),gec.mem.tooltip=null;else{gec.mem.tooltip&&gec.mem.tooltip.trigger(gec.mem.tooltip.data("event")+".libui");d=b.data("position")||"top";b.after(['<div class="ui-tooltip '+(b.data("extraclass")||"")+" ui-fade ui-"+d+'" style="position:absolute; ">','<div class="ui-arrow"></div>','<div class="ui-inner">'+(b.data("content")||b.attr("title"))+"</div>","</div>"].join(""));e=b.next();b.trigger("onrender",e);f=$.extend({},b.offset(),{width:a.offsetWidth,height:a.offsetHeight});g=
e[0].offsetWidth;h=e[0].offsetHeight;switch(d){case "bottom":k={top:f.top+f.height,left:f.left+f.width/2-g/2};break;case "top":k={top:f.top-h,left:f.left+f.width/2-g/2};break;case "left":k={top:f.top+f.height/2-h/2,left:f.left-g};break;case "right":k={top:f.top+f.height/2-h/2,left:f.left+f.width};break;case "center":k={top:f.top+f.height,left:0,width:"100%"}}e.offset(k).addClass("ui-in");"center"==d&&e.children(".ui-arrow").css({left:f.left});"click"==b.data("event")&&(gec.mem.tooltip=b)}});if("mouseenter"==
b.data("event"))b.on("mouseleave.libui",function(){b.next(".ui-tooltip").remove()});return b},orbit:function(a){function c(){var a,c,d;x?(c=m.parent().width(),a=l*c,c=a+c-s,0<c&&(a-=c),m.css({left:-1*a})):(y?(a=r[w][0]*l,c=a+r[w][0],u<c&&(a-=c-u),n.slice(a,c).each(function(){d=d>$(this).outerHeight(!0)?d:$(this).outerHeight(!0)})):d="auto",a=100*l,c=a+100-s,0<c&&(a-=c+v/t),a+=v*l,m.css({height:d,left:-1*a+"%"}));0<k.children().length&&k.children("li").removeClass("ui-active").eq(l).addClass("ui-active");
z&&b(l)}function b(a){a=n.eq(a);a.data("endAsync")||(a.find("img[data-src]").each(function(){$(this).attr("src",$(this).data("src")).removeAttr("data-src").addClass("lazy-loaded")}),a.data("endAsync",!0))}function d(){var b,d,e="",f;x?(s=0,n.each(function(){s+=$(this).width()}),m.width(s),f=Math.ceil(p=s/m.parent().width())):(f=r[w],t=f[0],b=f[1],v=f[2],s=Math.round((b+v)*u),f=Math.ceil(p=s/100),n.removeAttr("style"),m.removeAttr("style"),m.css("width",s+v*p+"%"),y&&setTimeout(function(){m.css({height:n.eq(0).outerHeight(!0)})},
500),d=gec.utils.round(100*v/b/u),b=100/u-d,n.css({width:b+"%","margin-right":(v?gec.utils.round(d):0)+"%"}),d=100-(d+gec.utils.round(b))*u,0!=d&&navigator.userAgent.match(/iPhone|iPad|iPod/i)&&n.css({width:b+1E-4+"%"}));k.empty();l=l>f?f-1:l;if(1<f){for(b=1;b<=f;b++)e+="<li>"+b+"</li>";k.html(e).children("li").on("click",function(a){a.preventDefault();a=$(this);a.hasClass("ui-active")||(l=a.prevAll().length,c())}).eq(l).trigger("click");k.show()}else h.hide(),k.hide();a.addClass("orbit-ed")}function e(){if(x)return d();
var a=$(window,document).width(),b=0,c;for(c in r){if(a>=b&&a<c){c!=w&&(w=c,d());break}b=c}}function f(){0<q&&setInterval(function(){$(".ui-next",h).trigger("click")},q)}function g(){var b=a.width(),d,e,g,k;m.on("touchstart touchend touchmove",function(a){switch(a.type){case "touchstart":k=a.originalEvent.touches[0].pageX;m.addClass("dragging");g=(new Date).getTime();break;case "touchmove":d=a.originalEvent.touches[0].pageX-k;(10<d||-10>d)&&a.preventDefault();e=100*d/b;m.css("left",-1*(100*l-e)+"%");
break;case "touchend":m.removeClass("dragging"),200>(new Date).getTime()-g?-20>e&&l+1<p?l+=1:20<e&&0<l&&(l-=1):-50>e&&l+1<p?l+=1:50<e&&0<l&&(l-=1),c(),f()}})}if(!(1>a.length||a.hasClass("orbit-ed"))){var h=a.find(".ui-arrows"),k=a.find(".ui-pager"),m=a.find(".ui-inner"),n=m.children(".ui-item"),u=n.length,r,w,l=0,s,v,t,p,q=1*(a.data("interval")||0),x="auto"==a.data("size"),y="auto"==a.data("height"),z=a.data("async")||0;if(y)a.on("heightAuto",function(){c()});x||(r=a.data("size")?a.data("size").replace(/:([\w\.]*)/g,
":[$1]").replace(/x/g,","):"3020:[1,100,0]",r=eval("[{"+r+"}]")[0]);$(".ui-prev, .ui-next",h).on("click.libui",function(a){a.preventDefault();a=Math.ceil(p);l+=$(this).hasClass("ui-prev")?-1:1;l=0>l?a-1:l>=a?0:l;c()});if("auto"==(a.data("resize")||"auto"))$(window).on("resize.libui",e);e();f();g()}},validate:function(a,c){var b=a.jquery?!1:(a=$(a),!0);a.each(function(){var a=$(this),b=$("[data-restrict],[data-require]",a);b.filter('[data-restrict]:not([data-restrict="email"])').on("keypress",function(b){gec.fn.validateControl(b,
this,a.data("show-message")||!1)});b.filter('[data-require],[data-restrict="email"]').on("blur",function(b){gec.fn.validateControl(b,this,a.data("show-message")||!1)});a.on("submit",function(f){if(!a.hasClass("noValidar")){b.filter('[data-require],[data-restrict="email"]').trigger("blur");if((f=0<$(".ui-error",a).length)||"function"!=typeof c)return!f;c(a);return!1}})});b&&(c.type&&c.preventDefault(),a.removeAttr("onsubmit").trigger("submit"))},tab:function(a,c){var b=$(a);if(gec.utils.eventBind({element:a,
event:c,ui:"tab",callback:function(a){a.element.removeAttr("onclick onmouseover").parent().siblings("li").children("a").removeAttr("onclick onmouseover");a.mom=a.element.closest(".ui-tab").data("event",c.type+".gecui");return a}}))return!1;b.data("event");$(">li>a",b).on(b.data("event"),function(a){a.preventDefault();a=$($(this).attr("href"));b.get(0).getAttribute("data-closing")&&a.hasClass("ui-active")?a.removeClass("ui-active"):($(".ui-panel",a.get(0).parentNode).removeClass("ui-active"),a.addClass("ui-active"));
b.get(0).getAttribute("data-closing")&&$(this).parent().hasClass("ui-active")?$(this).parent().removeClass("ui-active"):($("li",this.parentNode.parentNode).removeClass("ui-active"),$(this).parent().addClass("ui-active"))})},accordion:function(a,c){var b;if(gec.utils.eventBind({element:a,event:c,ui:"accordion",callback:function(a){a.element.removeAttr("onclick").parent().siblings(".ui-item").children(".ui-caption").removeAttr("onclick");a.mom=a.element.closest(".ui-accordion");return a}}))return!1;
b=a.children(".ui-item.ui-active");$(".ui-item>.ui-caption",a).on("click.gecui",function(a){var c=$(this),f=c.siblings(".ui-content"),g=c.parent().hasClass("ui-active");a.preventDefault();b&&b.removeClass("ui-active").children(".ui-content").show().slideUp("fast");b=null;if(g)return!1;f.slideDown("slow",function(){0<f.find(".ui-lazy").length&&$(window).trigger("scroll")});b=c.parent().addClass("ui-active")})},movilPopup:function(a){function c(a){a=a.find(".box-popup");var b=$(window).height()/2-a.outerHeight()/
2;a.css({top:0>b?0:b+"px"})}var b,d=function(){b=$('<div class="bloquer"><div class="box-popup" style="transition: top 0.5s ease; -webkit-transition: top 0.5s ease; "></div></div>');var c=$(".box-popup",b),d="object"==typeof a.target?a.target:$(a.target);d.find(".ui-cancel").on("click",function(a){a.preventDefault();b.remove();$(window).on("resize.gecui")});c.append(d);return b}();"function"==typeof a.callback&&a.callback(d);$("body").append(d);c(d);$(window).on("resize.gecui",function(){c(d)})}},
ready:function(a){var c=this;!0==this.loaded?a.apply(this):setTimeout(function(){a.apply(c)},200)},loaded:function(){var a=setInterval(function(){"function"==typeof jQuery&&(clearInterval(a),$(document).ready(function(a){gec.init();gec.loaded=!0}))},100)}(),init:function(){gec.env=gec.thisJs.src.match(/\/\/(dev|comercio3)/g)?"dev":gec.thisJs.src.match(/\/\/(pre)/g)?"pre":"pro";$.extend(jQuery.easing,{"default":function(a,c,b,d,e){return d*((c=c/e-1)*c*c*c*c+1)+b}});$.fn.orbit=function(){return this.each(function(){new gec.ui.orbit($(this))})};
this.fn.loadJs();this.nid=gec.thisJs.getAttribute("data-nid")||!1;this.fn.track({nid:!0});gec.fn.headershow();gec.utils.exec(gec.thisJs.getAttribute("data-ui"))}};gec.fn.otherJs.comments=function(){window.path_appc="//"+("pro"==gec.env||"dev"==gec.env||"s"==gec.env?"comments.ecoid.pe/":gec.env+".comments.ec.pe/");gec.path.comments=window.path_appc+"f/scripts/appcommentsv7.js";gec.fn.loadJs("comments")};
gec.fn.otherJs.cxense=function(){var a=document.createElement("div");a.id="cX-root";a.style.display="none";document.getElementsByTagName("body")[0].appendChild(a);var c=c||{};c.callQueue=c.callQueue||[];c.callQueue.push(["setAccountId","9222268904439147011"]);c.callQueue.push(["setSiteId","9222268904439147013"]);c.callQueue.push(["sendPageViewEvent"]);try{var b=document.createElement("script");b.type="text/javascript";b.async="async";b.src="https:"==document.location.protocol?"https://scdn.cxense.com/cx.js":
"http://cdn.cxense.com/cx.js";var d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d)}catch(e){}};
gec.fn.otherJs.peruid=function(){gec.path.peruid=0<="dev|pre".indexOf(gec.env)?"//"+gec.env+".s.peruid.pe/f/scripts/peruid-1.1.js":gec.path.peruid;gec.fn.loadJs("peruid");var a=setInterval(function(){"function"==typeof peruid&&(clearInterval(a),window.pid=new peruid({path_base:"//"+("pro"==gec.env||"s"==gec.env?"":gec.env+".")+"peruid.pe/",path_portal:"a94a8fe5ccb19ba61c4c0873d391e987982fbbd3",path_receiver:window.location.protocol+"//"+window.location.host+"/index.php/receiver/token/",path_proxy:window.location.protocol+
"//"+window.location.host+"/peruid_proxy.html",callback:function(a){var b=$("#user-info-movil"),d,e,f;e=$(".user-login");1==a.code||2==a.code?(a.j.usuario?(d=a.j.usuario.nombre||a.j.usuario.nombres,f=a.j.usuario.avatar||a.j.usuario.avatar):(e=unescape(document.cookie).match(/"nombres";s:\d+:"([^"]+)/)[1],f=unescape(document.cookie).match(/"avatar_url";s:\d+:"([^"]+)/)[1],e&&(d=e.replace("+"," "))),0<b.length&&(b.html(Array('<a class="foto_user" href="'+(1==a.j.status?"/cuenta/configuracion":pid.param.path_base+
"perfil/"+pid.param.path_portal)+"?path="+document.location.pathname+'"><img src="'+f+'" alt=""></a><span>'+d+"</span>").join("")),$("#ec-menu").append('<div class="logout-ec"><a href="'+pid.param.path_base+"logout/"+pid.param.path_portal+"?path="+document.location.pathname+'" class="item-menu">Cerrar sesi\u00f3n</a></div>')),pid.remove_modal()):(a=(a=b.data("redirect"))?'data-redirect="'+encodeURIComponent(a)+'"':"",d=(d=b.data("end-redirect"))?'data-end-redirect="'+encodeURIComponent(d)+'"':"",
0<b.length&&b.html(Array('<a class="icon-user go_peruid go-login" '+a+" "+d+' href="'+pid.param.path_base+"login/"+pid.param.path_portal+"?path="+document.location.pathname+"\" onclick=\"ga('send', 'event', 'Movil', 'Login', '"+window.location.pathname+"');\"></a>").join("")),e.addClass("go_peruid").attr("href",pid.param.path_base+"login/"+pid.param.path_portal+"?path="+document.location.pathname),pid.add_modal())}}))},200)};gec.fn.loadJs("jquery");document.write('<div id="cX-root" style="display:none"></div>');
var cX=cX||{};cX.callQueue=cX.callQueue||[];cX.callQueue.push(["setAccountId","9222268904439147011"]);cX.callQueue.push(["setSiteId","9222268904439147013"]);cX.callQueue.push(["sendPageViewEvent"]);(function(){try{var a=document.createElement("script");a.type="text/javascript";a.async="async";a.src="https:"==document.location.protocol?"https://scdn.cxense.com/cx.js":"http://cdn.cxense.com/cx.js";var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(a,c)}catch(b){}})();
var mb={sharemail:function(a,c){c.gesture&&(c.gesture.stopPropagation(),c.gesture.preventDefault());c.preventDefault();c.stopPropagation();var b=$(a),d,e,f=function(){var b=document.getElementById(a.getAttribute("data-toggle"));"share"!=b.getAttribute("state")?($(b).addClass("showshare"),b.setAttribute("state","share")):($(b).removeClass("showshare"),b.setAttribute("state",""))};d=['<form class="ui-form " data-show-message="true"><div class="ui-head">',"<span>"+(a.getAttribute("title")||"Compartir por e-mail")+
"</span>",'</div><div class="ui-body"><div class="ui-row"><input autocomplete="off" class="i_text" type="text" name="nombre" placeholder="Tu nombre" data-require="true"></div><div class="ui-row"><input autocomplete="off"  class="i_text" type="text" name="nombreamigo" placeholder="Nombre de tu amigo" data-require="true"></div><div class="ui-row"><input  class="i_text" type="text" name="emailamigo" placeholder="Email de tu amigo" data-restrict="email" data-require="true"></div>','<input type="hidden" name="titulo" value="'+
a.getAttribute("data-title")+'">','<input type="hidden" name="pagina" value="'+a.getAttribute("data-link")+'">','</div><div class="ui-foot ui-row"><button type="submit">Enviar</button></div></form>'].join("");e=document.createElement("div");e.className="box-send";e.innerHTML=d;var g=e.getElementsByTagName("form")[0],h=$(".i_text",g);h.each(function(){$(this).on("blur",function(a){gec.fn.validateControl(a,this,g.getAttribute("data-show-message")||!1)})});f();a.parentNode.appendChild(e);b.removeAttr("onclick").on("click",
function(a){a.gesture&&(a.gesture.stopPropagation(),a.gesture.preventDefault());a.preventDefault();a.stopPropagation();f()});$(g).on("submit",function(a){a.preventDefault();a.stopPropagation();h.each(function(){$(this).trigger("blur")});if(0<$(".ui-error",g).length)return!1;$.post(b.data("post"),$(g).serialize(),function(a){if(a.succes){var b=document.createElement("div");b.className="tx-message";b.innerHTML=a.message;$(".ui-body",g).get(0).appendChild(b)}setTimeout(function(){f();b.remove()},3E3);
h.val("")},"json")})}};
